In [4]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np

In [5]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
voc_size=10000

In [7]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3386, 3097, 3045, 9736],
 [3386, 3097, 3045, 5587],
 [3386, 9138, 3045, 6595],
 [6334, 8882, 2324, 4276, 1261],
 [6334, 8882, 2324, 4276, 2805],
 [493, 3386, 1783, 3045, 5076],
 [8300, 3234, 3967, 4276]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3386 3097 3045 9736]
 [   0    0    0    0 3386 3097 3045 5587]
 [   0    0    0    0 3386 9138 3045 6595]
 [   0    0    0 6334 8882 2324 4276 1261]
 [   0    0    0 6334 8882 2324 4276 2805]
 [   0    0    0  493 3386 1783 3045 5076]
 [   0    0    0    0 8300 3234 3967 4276]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\DELL\Desktop\Project\Deep Learning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 726ms/step


array([[[ 4.4090714e-02,  1.7962757e-02,  3.9259646e-02,  1.6175065e-02,
          2.8122928e-02, -2.1680593e-03, -2.8929783e-02,  1.5668180e-02,
          4.4993166e-02, -3.3106588e-02],
        [ 4.4090714e-02,  1.7962757e-02,  3.9259646e-02,  1.6175065e-02,
          2.8122928e-02, -2.1680593e-03, -2.8929783e-02,  1.5668180e-02,
          4.4993166e-02, -3.3106588e-02],
        [ 4.4090714e-02,  1.7962757e-02,  3.9259646e-02,  1.6175065e-02,
          2.8122928e-02, -2.1680593e-03, -2.8929783e-02,  1.5668180e-02,
          4.4993166e-02, -3.3106588e-02],
        [ 4.4090714e-02,  1.7962757e-02,  3.9259646e-02,  1.6175065e-02,
          2.8122928e-02, -2.1680593e-03, -2.8929783e-02,  1.5668180e-02,
          4.4993166e-02, -3.3106588e-02],
        [ 3.4217428e-02,  2.3993436e-02,  3.2764804e-02, -4.1140426e-02,
         -3.8513053e-02, -4.0243864e-03, -4.9042631e-02,  3.7958596e-02,
          6.6026822e-03,  1.9966807e-02],
        [-3.3452928e-02,  3.8812909e-02,  3.9378200e-02,  1.

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3386, 3097, 3045, 9736])

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step


array([[[ 4.4090714e-02,  1.7962757e-02,  3.9259646e-02,  1.6175065e-02,
          2.8122928e-02, -2.1680593e-03, -2.8929783e-02,  1.5668180e-02,
          4.4993166e-02, -3.3106588e-02],
        [ 4.4090714e-02,  1.7962757e-02,  3.9259646e-02,  1.6175065e-02,
          2.8122928e-02, -2.1680593e-03, -2.8929783e-02,  1.5668180e-02,
          4.4993166e-02, -3.3106588e-02],
        [ 4.4090714e-02,  1.7962757e-02,  3.9259646e-02,  1.6175065e-02,
          2.8122928e-02, -2.1680593e-03, -2.8929783e-02,  1.5668180e-02,
          4.4993166e-02, -3.3106588e-02],
        [ 4.4090714e-02,  1.7962757e-02,  3.9259646e-02,  1.6175065e-02,
          2.8122928e-02, -2.1680593e-03, -2.8929783e-02,  1.5668180e-02,
          4.4993166e-02, -3.3106588e-02],
        [ 3.4217428e-02,  2.3993436e-02,  3.2764804e-02, -4.1140426e-02,
         -3.8513053e-02, -4.0243864e-03, -4.9042631e-02,  3.7958596e-02,
          6.6026822e-03,  1.9966807e-02],
        [-3.3452928e-02,  3.8812909e-02,  3.9378200e-02,  1.